version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - 8000:8000
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin
  
  frontend:
    build:
      context: ./frontend/scratchandwin
    container_name: frontend
    volumes:
      - ./frontend/scratchandwin:/usr/src/app/frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
