# Generated by Django 3.2.7 on 2021-09-24 06:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='Claimed at')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=150, verbose_name='User Agent')),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon', verbose_name='Coupon')),
            ],
        ),
    ]
